title = "The 🥝 Blog"
baseURL = "https://gohugo-theme-ananke.pages.dev"
languageCode = "en-us"
theme = ["ananke"]

DefaultContentLanguage = "en"
SectionPagesMenu = "main"
Paginate = 6
googleAnalytics = ""
enableRobotsTXT = true

[languages]
[languages.en]
title = "The 🥝 Blog"
weight = 1
contentDir = "content/en"


[sitemap]
changefreq = "monthly"
priority = 0.5
filename = "sitemap.xml"

[params]
text_color = ""
author = "Jan Nox"
favicon = "/favicon.ico"
site_logo = ""
description = "The last theme you'll ever need. Maybe."
# choose a background color from any on this page: https://tachyons.io/docs/themes/skins/ and preface it with "bg-"
background_color_class = "bg-dark-gray"
recent_posts_number = 6

[[params.ananke_socials]]
name = "github"
url = "https://github.com/noxkiwi"
